### Bank Note Authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.

In [1]:
##Dataset Link: https://www.kaggle.com/ritesaluja/bank-note-authentication-uci-data
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('BankNote_Authentication.csv')

In [3]:
df

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [4]:
### Independent and Dependent features
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [5]:
X.head()

variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [6]:
y.head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: class, dtype: int64

In [7]:
### Train Test Split
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [9]:
### Implement Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [10]:
## Prediction
y_pred=classifier.predict(X_test)

In [11]:
### Check Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

In [12]:
score

0.9878640776699029

In [14]:
classifier.

RandomForestClassifier()

In [15]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("classifier.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

In [16]:
import numpy as np

In [17]:
classifier.predict([[2,3,4,1]])

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [27]:
classifier.predict(df.iloc[-1,:-1].values.reshape(1,-1))

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [26]:
df.iloc[-1,:-1].values.reshape(1,-1)

array([[-2.5419 , -0.65804,  2.6842 ,  1.1952 ]])

In [28]:
df

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [30]:
X,y

(      variance  skewness  curtosis  entropy
 0      3.62160   8.66610   -2.8073 -0.44699
 1      4.54590   8.16740   -2.4586 -1.46210
 2      3.86600  -2.63830    1.9242  0.10645
 3      3.45660   9.52280   -4.0112 -3.59440
 4      0.32924  -4.45520    4.5718 -0.98880
 ...        ...       ...       ...      ...
 1367   0.40614   1.34920   -1.4501 -0.55949
 1368  -1.38870  -4.87730    6.4774  0.34179
 1369  -3.75030 -13.45860   17.5932 -2.77710
 1370  -3.56370  -8.38270   12.3930 -1.28230
 1371  -2.54190  -0.65804    2.6842  1.19520
 
 [1372 rows x 4 columns],
 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1367    1
 1368    1
 1369    1
 1370    1
 1371    1
 Name: class, Length: 1372, dtype: int64)

creat a pipline for understanding how it works and if it works haha

In [31]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


In [45]:
scaler=StandardScaler()
x_scal=scaler.fit_transform(X)
x_scal

array([[ 1.12180565,  1.14945512, -0.97597007,  0.35456135],
       [ 1.44706568,  1.06445293, -0.89503626, -0.12876744],
       [ 1.20780971, -0.77735215,  0.12221838,  0.61807317],
       ...,
       [-1.47235682, -2.62164576,  3.75901744, -0.75488418],
       [-1.40669251, -1.75647104,  2.552043  , -0.04315848],
       [-1.04712236, -0.43982168,  0.29861555,  1.1364645 ]])

In [89]:
classi=pickle.load(open('classifier.pkl','rb'))

In [49]:
pca=PCA(n_components=0.90)
xpca=pca.fit_transform(x_scal)
xpca.shape

(1372, 3)

In [51]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [52]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


In [53]:
from sklearn.pipeline import Pipeline

In [54]:
pipe = Pipeline([('scaler', StandardScaler()), ('pca',PCA(n_components=0.9)),('clf', RandomForestClassifier())])

In [55]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=0.9)),
                ('clf', RandomForestClassifier())])

In [59]:
pipe.score(X_train,y_train)

1.0

In [60]:
pipe.score(X_test,y_test)

0.9733009708737864

In [61]:
pickle_out = open("clf_pipeline.pkl","wb")
pickle.dump(pipe, pickle_out)
pickle_out.close()

In [66]:
piplineclf=pickle.load(open('clf_pipeline.pkl','rb'))
clf_=pickle.load(open('classifier.pkl','rb'))

In [64]:
piplineclf.predict_proba([[1,2,3,4]])

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[0.23, 0.77]])

In [70]:
from sklearn.metrics import adjusted_rand_score

In [74]:
adjusted_rand_score(clf_.predict(X_test),y_test),adjusted_rand_score(piplineclf.predict(X_test),y_test),adjusted_rand_score(clf_.predict(X_test),piplineclf.predict(X_test))

(0.9519207307168713, 0.895791067083352, 0.8683639563856183)

In [79]:
dict(X_test.iloc[0])  

{'variance': -1.7713,
 'skewness': -10.7665,
 'curtosis': 10.2184,
 'entropy': -1.0043}

In [111]:
classi.predict_proba([[2,5,7,8]])

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[1., 0.]])

In [110]:
data=pd.DataFrame({
  "variance": 2,
  "skewness": 5,
  "curtosis": 7,
  "entropy": 8
})

ValueError: If using all scalar values, you must pass an index

In [109]:
type(int(classi.predict([[1,2,3,4]])[0]))

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


int

In [107]:
type(classi.predict_proba([[1,2,3,4]]).max())

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


numpy.float64

In [112]:
pipo=pickle.load(open('clf_pipeline.pkl','rb'))

In [114]:
pipo.predict(X_test.iloc[0].values.reshape(1,-1))

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [115]:
pipo.predict_proba(X_test.iloc[0].values.reshape(1,-1))

C:\Users\miche\anaconda3\envs\env_test\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[0.04, 0.96]])